name: Docker Image CI/CD
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}:latest

  pull-docker:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    needs: [build]
    name: Pull&Run Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Pull&Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd ~/simple_sql/
            sudo docker stop simple_sql
            sudo docker rm simple_sql
            sudo docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_REPOSITORY }}:latest
            sudo docker run \
            -itd --name simple_sql \
            --network=host \
            ${{ secrets.DOCKER_REPOSITORY }}:latest